# Generated by Django 4.2.17 on 2025-01-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    replaces = [('stock', '0001_initial'), ('stock', '0002_auto_20190525_2226'), ('stock', '0003_auto_20190525_2303'), ('stock', '0004_auto_20190525_2356'), ('stock', '0005_auto_20190602_1944'), ('stock', '0006_stockitem_purchase_order'), ('stock', '0007_auto_20190618_0042'), ('stock', '0008_stockitemtracking_url'), ('stock', '0009_auto_20190715_2351'), ('stock', '0010_stockitem_build'), ('stock', '0011_auto_20190908_0404'), ('stock', '0012_auto_20190908_0405'), ('stock', '0013_auto_20190908_0916'), ('stock', '0014_auto_20190908_0918'), ('stock', '0015_auto_20190913_1407'), ('stock', '0016_auto_20191118_2146'), ('stock', '0017_auto_20191118_2311'), ('stock', '0018_auto_20200202_0103'), ('stock', '0019_auto_20200202_1024'), ('stock', '0020_auto_20200206_1213'), ('stock', '0021_auto_20200215_2232'), ('stock', '0022_auto_20200217_1109'), ('stock', '0023_auto_20200318_1027'), ('stock', '0024_auto_20200405_2239'), ('stock', '0025_auto_20200405_2243'), ('stock', '0026_stockitem_uid'), ('stock', '0027_stockitem_sales_order'), ('stock', '0028_auto_20200421_0724'), ('stock', '0029_auto_20200421_2359'), ('stock', '0030_auto_20200422_0015'), ('stock', '0031_auto_20200422_0209'), ('stock', '0032_stockitem_build_order'), ('stock', '0033_auto_20200426_0539'), ('stock', '0034_auto_20200426_0602'), ('stock', '0035_auto_20200502_2308'), ('stock', '0036_stockitemattachment'), ('stock', '0037_stockitemattachment_user'), ('stock', '0038_stockitemattachment_upload_date'), ('stock', '0039_auto_20200513_0016'), ('stock', '0040_stockitemtestresult'), ('stock', '0041_stockitemtestresult_notes'), ('stock', '0042_auto_20200523_0121'), ('stock', '0043_auto_20200525_0420'), ('stock', '0044_auto_20200528_1036'), ('stock', '0045_stockitem_customer'), ('stock', '0046_auto_20200605_0931'), ('stock', '0047_auto_20200605_0932'), ('stock', '0048_auto_20200807_2344'), ('stock', '0049_auto_20200820_0454'), ('stock', '0050_auto_20200821_1403'), ('stock', '0051_auto_20200928_0928'), ('stock', '0052_stockitem_is_building'), ('stock', '0053_auto_20201110_0513'), ('stock', '0054_remove_stockitem_build_order'), ('stock', '0055_auto_20201117_1453'), ('stock', '0056_stockitem_expiry_date'), ('stock', '0057_stock_location_item_owner'), ('stock', '0058_stockitem_packaging'), ('stock', '0059_auto_20210404_2016'), ('stock', '0060_auto_20210511_1713'), ('stock', '0061_auto_20210511_0911'), ('stock', '0062_auto_20210511_2151'), ('stock', '0063_auto_20210511_2343'), ('stock', '0064_auto_20210621_1724'), ('stock', '0065_auto_20210701_0509'), ('stock', '0066_stockitem_scheduled_for_deletion'), ('stock', '0067_alter_stockitem_part'), ('stock', '0068_stockitem_serial_int'), ('stock', '0069_auto_20211109_2347'), ('stock', '0070_auto_20211128_0151'), ('stock', '0071_auto_20211205_1733'), ('stock', '0072_remove_stockitem_scheduled_for_deletion'), ('stock', '0073_alter_stockitem_belongs_to'), ('stock', '0074_alter_stockitem_batch'), ('stock', '0075_auto_20220515_1440'), ('stock', '0076_alter_stockitem_status'), ('stock', '0077_alter_stockitem_notes'), ('stock', '0078_alter_stockitem_supplier_part'), ('stock', '0079_alter_stocklocation_name'), ('stock', '0080_stocklocation_pathstring'), ('stock', '0081_auto_20220801_0044'), ('stock', '0082_alter_stockitem_link'), ('stock', '0083_stocklocation_icon'), ('stock', '0084_auto_20220903_0154'), ('stock', '0085_auto_20220903_0225'), ('stock', '0086_remove_stockitem_uid'), ('stock', '0087_auto_20220912_2341'), ('stock', '0088_remove_stockitem_infinite'), ('stock', '0089_alter_stockitem_purchase_price'), ('stock', '0090_stocklocation_structural'), ('stock', '0091_alter_stockitem_delete_on_deplete'), ('stock', '0092_alter_stockitem_updated'), ('stock', '0093_auto_20230217_2140'), ('stock', '0094_auto_20230220_0025'), ('stock', '0095_stocklocation_external'), ('stock', '0096_auto_20230330_1121'), ('stock', '0097_alter_stockitem_notes'), ('stock', '0098_auto_20230427_2033'), ('stock', '0099_alter_stockitem_status'), ('stock', '0100_auto_20230515_0004'), ('stock', '0100_stockitem_consumed_by'), ('stock', '0101_stockitemtestresult_metadata'), ('stock', '0102_alter_stockitem_status'), ('stock', '0103_stock_location_types'), ('stock', '0104_alter_stockitem_purchase_price_currency'), ('stock', '0105_stockitemtestresult_template'), ('stock', '0106_auto_20240207_0353'), ('stock', '0107_remove_stockitemtestresult_test_and_more'), ('stock', '0108_auto_20240219_0252'), ('stock', '0109_add_additional_test_fields'), ('stock', '0110_alter_stockitemtestresult_finished_datetime_and_more'), ('stock', '0111_delete_stockitemattachment'), ('stock', '0112_alter_stocklocation_custom_icon_and_more'), ('stock', '0113_stockitem_status_custom_key_and_more')]

    dependencies = [
        ("users", "0001_squashed"),
        ("part", "0003_squashed"),
        ("order", "0004_squashed"),
        ("stock", "0001_squashed"),
        ("company", "0002_squashed"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("build", "0004_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklocation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Select Owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_locations",
                to="users.owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="stock.stocklocation",
                verbose_name="parent",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtracking",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_info",
                to="stock.stockitem",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtracking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockitemtestresult",
            name="stock_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="stock.stockitem",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtestresult",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="part.parttesttemplate",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtestresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="belongs_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Is this item installed in another item?",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installed_parts",
                to="stock.stockitem",
                verbose_name="Installed In",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Build for this stock item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="build_outputs",
                to="build.build",
                verbose_name="Source Build",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="consumed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Build order which consumed this stock item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumed_stock",
                to="build.build",
                verbose_name="Consumed By",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer",
                limit_choices_to={"is_customer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_stock",
                to="company.company",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="location",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Where is this stock item located?",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="stock_items",
                to="stock.stocklocation",
                verbose_name="Stock Location",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Select Owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="users.owner",
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="stock.stockitem",
                verbose_name="Parent Stock Item",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="part",
            field=models.ForeignKey(
                help_text="Base part",
                limit_choices_to={"virtual": False},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="part.part",
                verbose_name="Base Part",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Purchase order for this stock item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="order.purchaseorder",
                verbose_name="Source Purchase Order",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="order.salesorder",
                verbose_name="Destination Sales Order",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="stocktake_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stocktake_stock",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="supplier_part",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a matching supplier part for this stock item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="company.supplierpart",
                verbose_name="Supplier Part",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
