# Generated by Django 5.2.12 on 2026-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0118_auto_20260205_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtestresult",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="stockitemtracking",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
    ]
