# Generated by Django 4.2.17 on 2025-01-05 01:26

import common.icons
import django.core.validators
import generic.states.fields
import generic.states.validators
from django.db import migrations, models

import stock.status_codes


class Migration(migrations.Migration):
    replaces = [
        ("stock", "0111_delete_stockitemattachment"),
        ("stock", "0112_alter_stocklocation_custom_icon_and_more"),
        ("stock", "0113_stockitem_status_custom_key_and_more"),
    ]

    dependencies = [
        ("company", "0069_company_active"),
        ("build", "0050_auto_20240508_0138"),
        ("stock", "0110_alter_stockitemtestresult_finished_datetime_and_more"),
        ("part", "0123_parttesttemplate_choices"),
        ("common", "0026_auto_20240608_1238"),
        ("order", "0099_alter_salesorder_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockItemAttachment",
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="custom_icon",
            field=models.CharField(
                blank=True,
                db_column="icon",
                help_text="Icon (optional)",
                max_length=100,
                validators=[common.icons.validate_icon],
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="stocklocationtype",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Default icon for all locations that have no icon set (optional)",
                max_length=100,
                validators=[common.icons.validate_icon],
                verbose_name="Icon",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="status_custom_key",
            field=generic.states.fields.ExtraInvenTreeCustomStatusModelField(
                blank=True,
                default=None,
                help_text="Additional status information for this item",
                null=True,
                validators=[
                    generic.states.validators.CustomStatusCodeValidator(
                        status_class=stock.status_codes.StockStatus
                    )
                ],
                verbose_name="Custom status key",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=generic.states.fields.InvenTreeCustomStatusModelField(
                choices=[
                    (10, "OK"),
                    (50, "Attention needed"),
                    (55, "Damaged"),
                    (60, "Destroyed"),
                    (65, "Rejected"),
                    (70, "Lost"),
                    (75, "Quarantined"),
                    (85, "Returned"),
                ],
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    generic.states.validators.CustomStatusCodeValidator(
                        status_class=stock.status_codes.StockStatus
                    ),
                ],
            ),
        ),
        migrations.AlterModelOptions(
            name="stockitem",
            options={"verbose_name": "Stock Item"},
        ),
        migrations.AlterModelOptions(
            name="stockitemtestresult",
            options={"verbose_name": "Stock Item Test Result"},
        ),
        migrations.AlterModelOptions(
            name="stockitemtracking",
            options={"verbose_name": "Stock Item Tracking"},
        ),
    ]
