version = 1
exclude_patterns = [
  "docs/docs/javascripts/**",                  # Docs: Helpers
  "docs/ci/**",                                # Docs: CI
  "src/backend/InvenTree/InvenTree/static/**", # Backend: CUI static files
  "src/backend/InvenTree/**/migrations/*.py",  # Backend: Migration files
  ".github/scripts/ci/**",                     # Backend: CI
  "src/frontend/src/locales/**",               # Frontend: Translations
]
test_patterns = ["**/test_*.py", "**/test.py", "**/tests.py"]


[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["react"]

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "test-coverage"
enabled = false
