# Path to sources
sonar.sources=InvenTree
sonar.exclusions=InvenTree/InvenTree/static/**
#sonar.inclusions=

# Path to tests
sonar.tests=InvenTree
sonar.test.exclusions=InvenTree/InvenTree/static/**
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
sonar.cpd.exclusions=InvenTree/InvenTree/static/**

sonar.python.version=3
