# Generated by Django 4.2.17 on 2025-01-05 12:47

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    replaces = [('company', '0001_initial'), ('company', '0002_auto_20190520_2204'), ('company', '0003_remove_supplierpart_minimum'), ('company', '0004_auto_20190525_2354'), ('company', '0005_auto_20190525_2356'), ('company', '0006_supplierpricebreak_currency'), ('company', '0007_remove_supplierpart_lead_time'), ('company', '0008_auto_20190913_1407'), ('company', '0009_auto_20191118_2323'), ('company', '0010_auto_20200201_1231'), ('company', '0011_auto_20200318_1114'), ('company', '0012_auto_20200318_1114'), ('company', '0013_auto_20200406_0131'), ('company', '0014_auto_20200407_0116'), ('company', '0015_company_is_manufacturer'), ('company', '0016_auto_20200412_2330'), ('company', '0017_auto_20200413_0320'), ('company', '0018_supplierpart_manufacturer'), ('company', '0019_auto_20200413_0642'), ('company', '0020_auto_20200413_0839'), ('company', '0021_remove_supplierpart_manufacturer_name'), ('company', '0022_auto_20200613_1045'), ('company', '0023_auto_20200808_0715'), ('company', '0024_unique_name_email_constraint'), ('company', '0025_auto_20201110_1001'), ('company', '0026_auto_20201110_1011'), ('company', '0027_remove_supplierpricebreak_currency'), ('company', '0028_remove_supplierpricebreak_cost'), ('company', '0029_company_currency'), ('company', '0030_auto_20201112_1112'), ('company', '0031_auto_20210103_2215'), ('company', '0032_auto_20210403_1837'), ('company', '0033_auto_20210410_1528'), ('company', '0034_manufacturerpart'), ('company', '0035_supplierpart_update_1'), ('company', '0036_supplierpart_update_2'), ('company', '0037_supplierpart_update_3'), ('company', '0038_manufacturerpartparameter'), ('company', '0039_auto_20210701_0509'), ('company', '0040_alter_company_currency'), ('company', '0041_alter_company_options'), ('company', '0042_supplierpricebreak_updated'), ('company', '0043_manufacturerpartattachment'), ('company', '0044_auto_20220607_2204'), ('company', '0045_alter_company_notes'), ('company', '0046_alter_company_image'), ('company', '0047_supplierpart_pack_size'), ('company', '0048_auto_20220913_0312'), ('company', '0049_company_metadata'), ('company', '0050_alter_company_website'), ('company', '0051_alter_supplierpricebreak_price'), ('company', '0052_alter_supplierpricebreak_updated'), ('company', '0053_supplierpart_updated'), ('company', '0054_companyattachment'), ('company', '0055_auto_20230317_0816'), ('company', '0056_alter_company_notes'), ('company', '0057_auto_20230427_2033'), ('company', '0058_auto_20230515_0004'), ('company', '0059_supplierpart_pack_units'), ('company', '0060_auto_20230519_0344'), ('company', '0061_remove_supplierpart_pack_size'), ('company', '0062_contact_metadata'), ('company', '0063_auto_20230502_1956'), ('company', '0064_move_address_field_to_address_model'), ('company', '0065_remove_company_address'), ('company', '0066_auto_20230616_2059'), ('company', '0067_alter_supplierpricebreak_price_currency'), ('company', '0068_auto_20231120_1108'), ('company', '0069_company_active'), ('company', '0070_remove_manufacturerpartattachment_manufacturer_part_and_more'), ('company', '0071_manufacturerpart_notes_supplierpart_notes')]

    dependencies = [
        ("part", "0001_squashed"),
        ("company", "0001_squashed"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpart",
            name="part",
            field=models.ForeignKey(
                help_text="Select part",
                limit_choices_to={"purchaseable": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_parts",
                to="part.part",
                verbose_name="Base Part",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="supplier",
            field=models.ForeignKey(
                help_text="Select supplier",
                limit_choices_to={"is_supplier": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_parts",
                to="company.company",
                verbose_name="Supplier",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpartparameter",
            name="manufacturer_part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="company.manufacturerpart",
                verbose_name="Manufacturer Part",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="manufacturer",
            field=models.ForeignKey(
                help_text="Select manufacturer",
                limit_choices_to={"is_manufacturer": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufactured_parts",
                to="company.company",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="part",
            field=models.ForeignKey(
                help_text="Select part",
                limit_choices_to={"purchaseable": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturer_parts",
                to="part.part",
                verbose_name="Base Part",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="company.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("name", "email"), name="unique_name_email_pair"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="company",
            field=models.ForeignKey(
                help_text="Select company",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="company.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplierpricebreak",
            unique_together={("part", "quantity")},
        ),
        migrations.AlterUniqueTogether(
            name="supplierpart",
            unique_together={("part", "supplier", "SKU")},
        ),
        migrations.AlterUniqueTogether(
            name="manufacturerpartparameter",
            unique_together={("manufacturer_part", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="manufacturerpart",
            unique_together={("part", "manufacturer", "MPN")},
        ),
    ]
