# Generated by Django 5.2.12 on 2026-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0079_auto_20260212_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
    ]
