# Generated by Django 4.2.17 on 2025-01-05 01:16

import InvenTree.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("company", "0047_supplierpart_pack_size"),
        ("company", "0048_auto_20220913_0312"),
        ("company", "0049_company_metadata"),
        ("company", "0050_alter_company_website"),
    ]

    dependencies = [
        ("company", "0046_alter_company_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpart",
            name="pack_size",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=1,
                help_text="Unit quantity supplied in a single pack",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.001)],
                verbose_name="Pack Quantity",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True, help_text="Company website URL", verbose_name="Website"
            ),
        ),
    ]
