# Generated by Django 4.2.17 on 2025-01-05 01:20

import InvenTree.fields
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        (
            "company",
            "0070_remove_manufacturerpartattachment_manufacturer_part_and_more",
        ),
        ("company", "0071_manufacturerpart_notes_supplierpart_notes"),
    ]

    dependencies = [
        ("build", "0050_auto_20240508_0138"),
        ("common", "0026_auto_20240608_1238"),
        ("company", "0069_company_active"),
        ("part", "0123_parttesttemplate_choices"),
        ("order", "0099_alter_salesorder_status"),
        ("stock", "0110_alter_stockitemtestresult_finished_datetime_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyAttachment",
        ),
        migrations.DeleteModel(
            name="ManufacturerPartAttachment",
        ),
        migrations.AddField(
            model_name="manufacturerpart",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="supplierpart",
            name="notes",
            field=InvenTree.fields.InvenTreeNotesField(
                blank=True,
                help_text="Markdown notes (optional)",
                max_length=50000,
                null=True,
                verbose_name="Notes",
            ),
        ),
    ]
