# Generated by Django 4.2.25 on 2025-10-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0142_remove_part_last_stocktake_remove_partstocktake_note_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partparameter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='part',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='template',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='partparametertemplate',
            name='selectionlist',
        ),
        migrations.DeleteModel(
            name='PartCategoryParameterTemplate',
        ),
        migrations.DeleteModel(
            name='PartParameter',
        ),
        migrations.DeleteModel(
            name='PartParameterTemplate',
        ),
    ]
