# Generated by Django 5.2.12 on 2026-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0147_remove_part_default_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomitem",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="bomitemsubstitute",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="partcategory",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="partcategoryparametertemplate",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="partrelated",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="parttesttemplate",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
    ]
