[project]
name = "docplugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.2"
dependencies = []

[project.entry-points."mkdocs.plugins"]
customplugin = "main:MyPlugin"
