# Generated by Django 4.2.17 on 2025-01-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("part", "0001_squashed"),
        ("order", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderlineitem",
            name="part",
            field=models.ForeignKey(
                help_text="Part",
                limit_choices_to={"salable": True, "virtual": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_line_items",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AddField(
            model_name="salesorderextraline",
            name="order",
            field=models.ForeignKey(
                help_text="Sales Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_lines",
                to="order.salesorder",
                verbose_name="Order",
            ),
        ),
    ]
