# Generated by Django 4.2.17 on 2025-01-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0002_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0002_squashed"),
        ("common", "0002_attachment_barcodescanresult_customunit_and_more"),
        ("stock", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderallocation",
            name="item",
            field=models.ForeignKey(
                help_text="Select stock item to allocate",
                limit_choices_to={
                    "belongs_to": None,
                    "part__salable": True,
                    "part__virtual": False,
                    "sales_order": None,
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_order_allocations",
                to="stock.stockitem",
                verbose_name="Item",
            ),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="order.salesorderlineitem",
                verbose_name="Line",
            ),
        ),
        migrations.AddField(
            model_name="salesorderallocation",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales order shipment reference",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="order.salesordershipment",
                verbose_name="Shipment",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Company address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Point of contact for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                help_text="Company to which the items are being sold",
                limit_choices_to={"is_customer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_orders",
                to="company.company",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
    ]
