# Generated by Django 4.2.17 on 2025-01-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    replaces = [('order', '0001_initial'), ('order', '0002_auto_20190604_2224'), ('order', '0003_auto_20190604_2226'), ('order', '0004_purchaseorder_status'), ('order', '0005_purchaseorderlineitem_part'), ('order', '0006_auto_20190605_2056'), ('order', '0007_auto_20190605_2138'), ('order', '0008_auto_20190605_2140'), ('order', '0009_auto_20190606_2133'), ('order', '0010_purchaseorderlineitem_notes'), ('order', '0011_auto_20190615_1928'), ('order', '0012_auto_20190617_1943'), ('order', '0013_auto_20191118_2323'), ('order', '0014_auto_20191118_2328'), ('order', '0015_auto_20200201_2346'), ('order', '0016_purchaseorderattachment'), ('order', '0017_auto_20200331_1000'), ('order', '0018_auto_20200406_0151'), ('order', '0019_purchaseorder_supplier_reference'), ('order', '0020_auto_20200420_0940'), ('order', '0021_auto_20200420_1010'), ('order', '0022_salesorderlineitem_part'), ('order', '0023_auto_20200420_2309'), ('order', '0024_salesorderallocation'), ('order', '0025_auto_20200422_0222'), ('order', '0026_auto_20200422_0224'), ('order', '0027_auto_20200422_0236'), ('order', '0028_auto_20200423_0956'), ('order', '0029_auto_20200423_1042'), ('order', '0030_auto_20200426_0551'), ('order', '0031_auto_20200426_0612'), ('order', '0032_auto_20200427_0044'), ('order', '0033_auto_20200512_1033'), ('order', '0034_auto_20200512_1054'), ('order', '0035_auto_20200513_0016'), ('order', '0036_auto_20200831_0912'), ('order', '0037_auto_20201110_0911'), ('order', '0038_auto_20201112_1737'), ('order', '0039_auto_20201112_2203'), ('order', '0040_salesorder_target_date'), ('order', '0041_auto_20210114_1728'), ('order', '0042_auto_20210310_1619'), ('order', '0043_auto_20210330_0013'), ('order', '0044_auto_20210404_2016'), ('order', '0045_auto_20210504_1946'), ('order', '0046_purchaseorderlineitem_destination'), ('order', '0047_auto_20210701_0509'), ('order', '0048_auto_20210702_2321'), ('order', '0049_alter_purchaseorderlineitem_unique_together'), ('order', '0050_alter_purchaseorderlineitem_destination'), ('order', '0051_auto_20211014_0623'), ('order', '0052_auto_20211014_0631'), ('order', '0053_auto_20211128_0151'), ('order', '0053_salesordershipment'), ('order', '0054_salesorderallocation_shipment'), ('order', '0055_auto_20211025_0645'), ('order', '0056_alter_salesorderallocation_shipment'), ('order', '0057_salesorderlineitem_shipped'), ('order', '0058_auto_20211126_1210'), ('order', '0059_salesordershipment_tracking_number'), ('order', '0060_auto_20211129_1339'), ('order', '0054_auto_20211201_2139'), ('order', '0061_merge_0054_auto_20211201_2139_0060_auto_20211129_1339'), ('order', '0062_auto_20220228_0321'), ('order', '0063_alter_purchaseorderlineitem_unique_together'), ('order', '0064_purchaseorderextraline_salesorderextraline'), ('order', '0065_alter_purchaseorderlineitem_part'), ('order', '0066_alter_purchaseorder_supplier'), ('order', '0067_auto_20220516_1120'), ('order', '0068_alter_salesorderallocation_unique_together'), ('order', '0069_auto_20220524_0508'), ('order', '0070_auto_20220620_0728'), ('order', '0071_auto_20220628_0133'), ('order', '0072_alter_salesorder_reference'), ('order', '0073_alter_purchaseorder_reference'), ('order', '0074_auto_20220709_0108'), ('order', '0075_auto_20221110_0108'), ('order', '0076_auto_20221111_0153'), ('order', '0077_auto_20230129_0154'), ('order', '0078_auto_20230304_0721'), ('order', '0079_auto_20230304_0904'), ('order', '0080_auto_20230317_0816'), ('order', '0081_auto_20230314_0725'), ('order', '0082_auto_20230314_1259'), ('order', '0083_returnorderextraline'), ('order', '0084_auto_20230321_1111'), ('order', '0085_auto_20230322_1056'), ('order', '0086_auto_20230323_1108'), ('order', '0087_alter_salesorder_status'), ('order', '0088_auto_20230403_1402'), ('order', '0089_auto_20230404_0030'), ('order', '0090_auto_20230412_1752'), ('order', '0091_auto_20230419_0037'), ('order', '0092_auto_20230419_0250'), ('order', '0093_auto_20230426_0248'), ('order', '0094_auto_20230514_2331'), ('order', '0095_salesordershipment_delivery_date'), ('order', '0096_alter_returnorderlineitem_outcome'), ('order', '0097_auto_20230529_0107'), ('order', '0098_auto_20231024_1844'), ('order', '0099_alter_salesorder_status'), ('order', '0100_remove_returnorderattachment_order_and_more'), ('order', '0101_purchaseorder_status_custom_key_and_more'), ('order', '0102_purchaseorder_destination_and_more'), ('order', '0103_alter_salesorderallocation_shipment'), ('order', '0104_alter_returnorderlineitem_quantity'), ('order', '0105_auto_20241128_0431')]


    dependencies = [
        ("users", "0001_squashed"),
        ("company", "0002_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_attachment_barcodescanresult_customunit_and_more"),
        ("stock", "0001_squashed"),
        ("order", "0003_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="shipped by",
            ),
        ),
        migrations.AddField(
            model_name="returnorderlineitem",
            name="item",
            field=models.ForeignKey(
                help_text="Select item to return from customer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_order_lines",
                to="stock.stockitem",
                verbose_name="Item",
            ),
        ),
        migrations.AddField(
            model_name="returnorderlineitem",
            name="order",
            field=models.ForeignKey(
                help_text="Return Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="order.returnorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="returnorderextraline",
            name="order",
            field=models.ForeignKey(
                help_text="Return Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_lines",
                to="order.returnorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Company address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Point of contact for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="customer",
            field=models.ForeignKey(
                help_text="Company from which items are being returned",
                limit_choices_to={"is_customer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="company.company",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="destination",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Destination for received items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_lines",
                to="stock.stocklocation",
                verbose_name="Destination",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="order",
            field=models.ForeignKey(
                help_text="Purchase Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="order.purchaseorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="part",
            field=models.ForeignKey(
                help_text="Supplier part",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_line_items",
                to="company.supplierpart",
                verbose_name="Part",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderextraline",
            name="order",
            field=models.ForeignKey(
                help_text="Purchase Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_lines",
                to="order.purchaseorder",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Company address for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.address",
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Point of contact for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="company.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="destination",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Destination for received items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="stock.stocklocation",
                verbose_name="Destination",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Select project code for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.projectcode",
                verbose_name="Project Code",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Company from which the items are being ordered",
                limit_choices_to={"is_supplier": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="company.company",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesordershipment",
            unique_together={("order", "reference")},
        ),
        migrations.AlterUniqueTogether(
            name="returnorderlineitem",
            unique_together={("order", "item")},
        ),
    ]
