# Generated by Django 5.2.12 on 2026-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0115_purchaseorder_updated_at_returnorder_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderextraline",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="returnorder",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="returnorderextraline",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="returnorderlineitem",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="salesorderextraline",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="salesordershipment",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
    ]
