# Generated by Django 4.2.17 on 2025-01-04 17:11

import InvenTree.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import mptt.fields


class Migration(migrations.Migration):

    replaces = [
        ("order", "0031_auto_20200426_0612"),
        ("order", "0032_auto_20200427_0044"),
        ("order", "0033_auto_20200512_1033"),
        ("order", "0034_auto_20200512_1054"),
        ("order", "0035_auto_20200513_0016"),
        ("order", "0036_auto_20200831_0912"),
        ("order", "0037_auto_20201110_0911"),
        ("order", "0038_auto_20201112_1737"),
        ("order", "0039_auto_20201112_2203"),
        ("order", "0040_salesorder_target_date"),
        ("order", "0041_auto_20210114_1728"),
        ("order", "0042_auto_20210310_1619"),
        ("order", "0043_auto_20210330_0013"),
        ("order", "0044_auto_20210404_2016"),
        ("order", "0045_auto_20210504_1946"),
        ("order", "0046_purchaseorderlineitem_destination"),
        ("order", "0047_auto_20210701_0509"),
        ("order", "0048_auto_20210702_2321"),
        ("order", "0049_alter_purchaseorderlineitem_unique_together"),
        ("order", "0050_alter_purchaseorderlineitem_destination"),
    ]

    dependencies = [
        ("company", "0023_auto_20200808_0715"),
        ("stock", "0034_auto_20200426_0602"),
        ("part", "0063_bomitem_inherited"),
        ("order", "0030_auto_20200426_0551"),
        ("common", "0004_inventreesetting"),
        ("company", "0032_auto_20210403_1837"),
        ("company", "0040_alter_company_currency"),
        ("part", "0035_auto_20200406_0045"),
        ("stock", "0063_auto_20210511_2343"),
        ("users", "0005_owner_model"),
        ("stock", "0058_stockitem_packaging"),
        ("stock", "0065_auto_20210701_0509"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0054_remove_stockitem_build_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderallocation",
            name="item",
            field=models.ForeignKey(
                help_text="Select stock item to allocate",
                limit_choices_to={
                    "belongs_to": None,
                    "build_order": None,
                    "part__salable": True,
                    "sales_order": None,
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_order_allocations",
                to="stock.stockitem",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderattachment",
            name="comment",
            field=models.CharField(
                blank=True, help_text="File comment", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="comment",
            field=models.CharField(
                blank=True, help_text="File comment", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="complete_date",
            field=models.DateField(
                blank=True, help_text="Date order was completed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateField(
                blank=True, help_text="Date order was issued", null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Company from which the items are being ordered",
                limit_choices_to={"is_supplier": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                help_text="Company to which the items are being sold",
                limit_choices_to={"is_customer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="item",
            field=models.ForeignKey(
                help_text="Select stock item to allocate",
                limit_choices_to={
                    "belongs_to": None,
                    "part__salable": True,
                    "sales_order": None,
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_order_allocations",
                to="stock.stockitem",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for order completion. Order will be overdue after this date.",
                null=True,
                verbose_name="Target completion date",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Expected date for order delivery. Order will be overdue after this date.",
                null=True,
                verbose_name="Target Delivery Date",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="complete_date",
            field=models.DateField(
                blank=True,
                help_text="Date order was completed",
                null=True,
                verbose_name="Completion Date",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateField(
                blank=True,
                help_text="Date order was issued",
                null=True,
                verbose_name="Issue Date",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                help_text="User or group responsible for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.owner",
                verbose_name="Responsible",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesorderlineitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="description",
            field=models.CharField(
                help_text="Order description",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link to external page", verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Order notes", verbose_name="Notes"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="reference",
            field=models.CharField(
                help_text="Order reference",
                max_length=64,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                help_text="Company from which the items are being ordered",
                limit_choices_to={"is_supplier": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="company.company",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier_reference",
            field=models.CharField(
                blank=True,
                help_text="Supplier order reference code",
                max_length=64,
                verbose_name="Supplier Reference",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderattachment",
            name="attachment",
            field=models.FileField(
                help_text="Select file to attach",
                upload_to="attachments",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderattachment",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="File comment",
                max_length=100,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderattachment",
            name="upload_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="upload date"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Line item notes",
                max_length=500,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="order",
            field=models.ForeignKey(
                help_text="Purchase Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="order.purchaseorder",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="part",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier part",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_line_items",
                to="company.supplierpart",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="quantity",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=1,
                help_text="Item quantity",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="received",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                help_text="Number of items received",
                max_digits=15,
                verbose_name="Received",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderlineitem",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Line item reference",
                max_length=100,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Creation Date"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                help_text="Company to which the items are being sold",
                limit_choices_to={"is_customer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="company.company",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="customer_reference",
            field=models.CharField(
                blank=True,
                help_text="Customer order reference code",
                max_length=64,
                verbose_name="Customer Reference ",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="description",
            field=models.CharField(
                help_text="Order description",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link to external page", verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Order notes", verbose_name="Notes"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="reference",
            field=models.CharField(
                help_text="Order reference",
                max_length=64,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="shipment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Shipment Date"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="shipped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="shipped by",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "Pending"),
                    (20, "Shipped"),
                    (40, "Cancelled"),
                    (50, "Lost"),
                    (60, "Returned"),
                ],
                default=10,
                help_text="Purchase order status",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="item",
            field=models.ForeignKey(
                help_text="Select stock item to allocate",
                limit_choices_to={
                    "belongs_to": None,
                    "part__salable": True,
                    "sales_order": None,
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_order_allocations",
                to="stock.stockitem",
                verbose_name="Item",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="order.salesorderlineitem",
                verbose_name="Line",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderallocation",
            name="quantity",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=1,
                help_text="Enter stock allocation quantity",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="attachment",
            field=models.FileField(
                help_text="Select file to attach",
                upload_to="attachments",
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderattachment",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="File comment",
                max_length=100,
                verbose_name="Comment",
            ),
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="upload_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="upload date"
            ),
        ),
        migrations.AddField(
            model_name="salesorderattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Line item notes",
                max_length=500,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="order",
            field=models.ForeignKey(
                help_text="Sales Order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="order.salesorder",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="part",
            field=models.ForeignKey(
                help_text="Part",
                limit_choices_to={"salable": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_line_items",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="quantity",
            field=InvenTree.fields.RoundingDecimalField(
                decimal_places=5,
                default=1,
                help_text="Item quantity",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderlineitem",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Line item reference",
                max_length=100,
                verbose_name="Reference",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="purchase_price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=4,
                default_currency="",
                help_text="Unit purchase price",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Purchase Price",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="purchase_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="sale_price",
            field=InvenTree.fields.InvenTreeModelMoneyField(
                blank=True,
                currency_choices=[],
                decimal_places=4,
                default_currency="",
                help_text="Unit sale price",
                max_digits=19,
                null=True,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
                verbose_name="Sale Price",
            ),
        ),
        migrations.AddField(
            model_name="salesorderlineitem",
            name="sale_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[], default="", editable=False, max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="reference",
            field=models.CharField(
                default="PO",
                help_text="Order reference",
                max_length=64,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="reference",
            field=models.CharField(
                default="SO",
                help_text="Order reference",
                max_length=64,
                unique=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderlineitem",
            unique_together={("order", "part", "quantity", "purchase_price")},
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="destination",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Where does the Purchaser want this item to be stored?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_lines",
                to="stock.stocklocation",
                verbose_name="Destination",
            ),
        ),
    ]
