# Generated by Django 5.2.12 on 2026-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_auto_20251203_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="barcodescanresult",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="emailthread",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="parameter",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="parametertemplate",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="projectcode",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
        migrations.AddField(
            model_name="selectionlist",
            name="metadata_id",
            field=models.CharField(
                editable=False,
                help_text="Globally unique identifier",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Metadata ID",
            ),
        ),
    ]
