# Generated by Django 5.2.15 on 2026-07-03 22:53

import InvenTree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0045_projectcode_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the dialog profile",
                        max_length=100,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the dialog profile",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Is this dialog profile enabled?",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON definition for the dialog profile",
                        verbose_name="Definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dialog Profile",
                "verbose_name_plural": "Dialog Profiles",
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
    ]
