# Generated by Django 5.2.15 on 2026-06-07 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_userprofile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="pepper_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the pepper used to hash the token",
                max_length=50,
                verbose_name="Pepper ID",
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="token_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hashed value of the token (for v2 tokens)",
                max_length=128,
                verbose_name="Token Hash",
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Token version (1 for plaintext, 2 for hashed)",
                verbose_name="Version",
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="key",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(50)],
                verbose_name="Key",
            ),
        ),
    ]
