# Generated by Django 4.2.17 on 2025-01-04 13:09

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_auto_20201004_0158"),
        ("users", "0003_auto_20201005_2227"),
        ("users", "0004_auto_20210113_1909"),
        ("users", "0005_owner_model"),
        ("users", "0006_alter_ruleset_name"),
        ("users", "0007_alter_ruleset_name"),
        ("users", "0008_apitoken"),
        ("users", "0009_auto_20231020_2356"),
        ("users", "0010_alter_apitoken_key"),
        ("users", "0011_auto_20240523_1640"),
        ("users", "0012_alter_ruleset_can_view"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("part_category", "Part Categories"),
                            ("part", "Parts"),
                            ("stock_location", "Stock Locations"),
                            ("stock", "Stock Items"),
                            ("build", "Build Orders"),
                            ("purchase_order", "Purchase Orders"),
                            ("sales_order", "Sales Orders"),
                        ],
                        help_text="Permission set",
                        max_length=50,
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=True,
                        help_text="Permission to view items",
                        verbose_name="View",
                    ),
                ),
                (
                    "can_add",
                    models.BooleanField(
                        default=False,
                        help_text="Permission to add items",
                        verbose_name="Add",
                    ),
                ),
                (
                    "can_change",
                    models.BooleanField(
                        default=False,
                        help_text="Permissions to edit items",
                        verbose_name="Change",
                    ),
                ),
                (
                    "can_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Permission to delete items",
                        verbose_name="Delete",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_sets",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "group")},
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "owner_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.UniqueConstraint(
                fields=("owner_type", "owner_id"), name="unique_owner"
            ),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("part_category", "Part Categories"),
                    ("part", "Parts"),
                    ("stocktake", "Stocktake"),
                    ("stock_location", "Stock Locations"),
                    ("stock", "Stock Items"),
                    ("build", "Build Orders"),
                    ("purchase_order", "Purchase Orders"),
                    ("sales_order", "Sales Orders"),
                ],
                help_text="Permission set",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("part_category", "Part Categories"),
                    ("part", "Parts"),
                    ("stocktake", "Stocktake"),
                    ("stock_location", "Stock Locations"),
                    ("stock", "Stock Items"),
                    ("build", "Build Orders"),
                    ("purchase_order", "Purchase Orders"),
                    ("sales_order", "Sales Orders"),
                    ("return_order", "Return Orders"),
                ],
                help_text="Permission set",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=users.models.default_token,
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(50)],
                        verbose_name="Key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Custom token name",
                        max_length=100,
                        verbose_name="Token Name",
                    ),
                ),
                (
                    "expiry",
                    models.DateField(
                        default=users.models.default_token_expiry,
                        help_text="Token expiry date",
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Token has been revoked",
                        verbose_name="Revoked",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "last_seen",
                    models.DateField(
                        blank=True,
                        help_text="Last time the token was used",
                        null=True,
                        verbose_name="Last Seen",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="JSON metadata field, for use by external plugins",
                        null=True,
                        verbose_name="Plugin Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
                "abstract": False,
                "unique_together": set(),
            },
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="can_view",
            field=models.BooleanField(
                default=False, help_text="Permission to view items", verbose_name="View"
            ),
        ),
    ]
