name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          OTLP_HEADERS: ${{ secrets.OTLP_HEADERS }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add OTLP_HEADERS="$OTLP_HEADERS" SONAR_TOKEN="$SONAR_TOKEN" --repo matmair/InvenTree
