name: Make Translation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_DB_NAME: './test_db.sqlite'
      INVENTREE_DB_ENGINE: django.db.backends.sqlite3
      INVENTREE_DEBUG: info
      INVENTREE_MEDIA_ROOT: ./media
      INVENTREE_STATIC_ROOT: ./static

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          pip3 install invoke
          invoke install
    - name: Make Translations
      run: |
        cd InvenTree
        python manage.py makemessages -e py -e html -e js
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.10.0
      with:
        commit_message: updated translation-string
        branch: l10_base
        file_pattern: *.po
