name: Update dependency files regularly

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445 # pin@v2
      - name: Setup
        run: pip install -r requirements-dev.txt
      - name: Update requirements.txt
        run: pip-compile --output-file=requirements.txt requirements.in -U
      - name: Update requirements-dev.txt
        run: pip-compile --generate-hashes --output-file=requirements-dev.txt
          requirements-dev.in -U
      - uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # pin@v4
        with:
          commit_message: "[Bot] Updated dependency"
          branch: dep-update
